"""Покрытие: какие Википедии есть на витрине, какие в очереди, где площадки нет.

Снимок разведки 27–28.09.2026 (43 вики) (stuff/Projects/toolforge/25, 26; data/cee-survey/<db>.md):
активные участники за 30 дней по siteinfo, площадка, удаление шаблоном без обсуждения
(PROD, метка значимости) и объём обсуждений шкалой — по API. Это справочная таблица для обзора;
обновляется руками при новой разведке.

volume: none — обсуждений нет; low — меньше 10 в месяц; medium — 10–99; high — 100 и больше.

plan: live — раздел в проде; next — в очереди этапа 3; later — площадка есть, но
объём единицы в месяц; log-only — работающей площадки обсуждений нет, только журнал.
"""

from __future__ import annotations

from urllib.parse import quote

SURVEYED_ON = "2026-09-27/28"

#: (dbname, active editors, venue title or None, how nominations are listed,
#:  deletion by tag without discussion or None, discussion volume, plan)
SURVEY: list[tuple[str, int, str | None, str, str | None, str, str]] = [
    ("eswiki", 38963, "Wikipedia:Consultas de borrado", "subpages per nomination, found via category; archive by month", "PROD, 7 days; 30-day tags for notability and sources (the bigger route)", "medium", "next"),
    ("frwiki", 34548, "Wikipédia:Débat d'admissibilité", "discussion on the article's talk subpage; live board of links by day", None, "high", "next"),
    ("plwiki", 8856, "Wikipedia:Poczekalnia/artykuły", "dated subpages on a permanent hub, monthly archive", None, "high", "next"),
    ("nlwiki", 7864, "Wikipedia:Te beoordelen pagina's", "one page per day (same shape as en/it/ja); no outcome in text, fate from the log", None, "high", "next"),
    ("ptwiki", 7598, "Wikipédia:Páginas para eliminar", "subpages per nomination, found via category; archive by year", "ESR (unreviewed translations); bigger than the venue", "high", "next"),
    ("fawiki", 7296, "ویکی‌پدیا:نظرخواهی برای حذف", "permanent hub + subpages; creation-month category", "PROD", "high", "next"),
    ("hewiki", 6628, "ויקיפדיה:מדיניות המחיקה", "formal vote (55 %) only after a notability discussion; vote subpages via a year category", "notability tag {{חשיבות}} + a week on the article's talk page; the main route", "medium", "later"),
    ("arwiki", 5600, "ويكيبيديا:نقاش الحذف", "subpages transcluded on one board", "PROD, unused", "medium", "next"),
    ("kowiki", 5078, "위키백과:삭제 토론", "monthly subpages transcluding nominations (same shape as en/it/ja)", "PROD, 7 days", "low", "next"),
    ("viwiki", 5054, "Wikipedia:Biểu quyết xoá bài", "permanent hub grouped by month, archived by month", "PROD", "medium", "next"),
    ("idwiki", 4920, "Wikipedia:Usulan penghapusan", "subpages found via category; no outcome in text, fate from the log", "PROD folded into the venue", "medium", "next"),
    ("svwiki", 4891, "Wikipedia:Sidor föreslagna för radering", "permanent hub + subpages; archive by closing month", None, "low", "later"),
    ("trwiki", 4213, "Vikipedi:Silinmeye aday sayfalar", "permanent hub, monthly archive", "PROD (bekletmeli sil), 5 days", "high", "next"),
    ("cswiki", 4123, "Wikipedie:Diskuse o smazání", "subpages transcluded on a hub list", "PROD, seven tag templates", "medium", "next"),
    ("fiwiki", 3536, "Wikipedia:Poistoäänestykset", "queue + yearly category; vote with 70 % threshold", None, "low", "later"),
    ("simplewiki", 3268, "Wikipedia:Requests for deletion", "queue + subpages Requests/<year>/<title>; closing templates as on en", None, "medium", "next"),
    ("huwiki", 2714, "Wikipédia:Törlésre javasolt lapok", "subpages on a hub grouped by date, monthly archive category", "PROD; expiring drafts outnumber discussions", "medium", "next"),
    ("thwiki", 2623, None, "a translated policy page with no process behind it; all deletions speedy", None, "none", "log-only"),
    ("nowiki", 2341, "Wikipedia:Sletting", "queue; a bot archives closed cases by outcome and month; outcome in the heading as on de", None, "medium", "next"),
    ("elwiki", 2270, "Βικιπαίδεια:Σελίδες για διαγραφή", "discussion on the article's talk subpage, monthly index", None, "low", "next"),
    ("mswiki", 2029, "Wikipedia:Permohonan memadam laman", "daily-log shape with links to pages that do not exist", "PROD exists, unused", "low", "later"),
    ("cawiki", 1787, "Viquipèdia:Esborrar pàgines/Propostes", "sections on one page, monthly archive; one admin closes", "7-day waits built into some speedy criteria", "low", "later"),
    ("bnwiki", 1735, "উইকিপিডিয়া:নিবন্ধ অপসারণের প্রস্তাবনা", "monthly pages titled with Bengali digits", "PROD inside the venue, unused", "low", "later"),
    ("rowiki", 1703, "Wikipedia:Pagini de șters", "subpages transcluded on a hub, monthly ledger of outcomes", None, "low", "next"),
    ("bgwiki", 1667, "Уикипедия:Страници за изтриване", "dated subpages on a permanent hub", "tag for micro-stubs", "low", "next"),
    ("dawiki", 1659, "Wikipedia:Sletningsforslag", "sections generated by the nomination template, numbered archives; anyone may close", None, "medium", "next"),
    ("srwiki", 1619, "Википедија:Чланци за брисање", "sections on one page, numbered archives; outcome computed from votes", None, "low", "later"),
    ("skwiki", 1198, "Wikipédia:Stránky na zmazanie", "subpages on a hub, yearly archive", "{{Urgentne upraviť}}, 14 days; the main route", "low", "next"),
    ("hiwiki", 1115, "विकिपीडिया:पृष्ठ हटाने हेतु चर्चा", "found via category; two competing monthly-log formats; closed with XFDcloser", None, "medium", "later"),
    ("etwiki", 976, None, "no central venue: article talk page + queue category (624 pages)", "notability tag + article talk page; the main route", "medium", "log-only"),
    ("hrwiki", 953, "Wikipedija:Rasprava o brisanju", "one page per month, sections", None, "medium", "next"),
    ("azwiki", 849, "Vikipediya:Silinməyə namizəd səhifələr", "subpages transcluded on a hub", None, "low", "next"),
    ("ltwiki", 624, None, "venue dead since 2009; tag + queue category, voting banned", "tag + queue category; the only route", "none", "log-only"),
    ("slwiki", 591, "Wikipedija:Predlogi za brisanje", "subpages on a hub grouped by month", None, "low", "later"),
    ("uzwiki", 579, "Vikipediya:Oʻchirishga", "subpages transcluded on a hub", None, "low", "later"),
    ("hywiki", 552, "Վիքիպեդիա:Ջնջման առաջադրված հոդվածներ", "sections on one page; outcome computed from votes (75 %)", "de facto: «no sources, 7 days», seen only in the log", "low", "next"),
    ("lvwiki", 498, None, "PROD tag; the voting hub has not handled articles since 2013", "{{Dzēst}}, flexible deadline; the only route", "none", "log-only"),
    ("bewiki", 399, "Вікіпедыя:Да выдалення", "sections on one page, yearly archive", None, "low", "later"),
    ("sqwiki", 370, "Wikipedia:Forumi i Grisjes", "register page, numbered archives", None, "low", "later"),
    ("kkwiki", 369, None, "no venue: the community declined one in 2020", None, "none", "log-only"),
    ("kawiki", 346, "ვიკიპედია:წაშლილი გვერდების განხილვები", "link hub → subpages; unused", None, "none", "log-only"),
    ("mkwiki", 324, "Википедија:Статии за бришење", "one page, dead since 2013", None, "none", "log-only"),
    ("bswiki", 257, None, "rules page only; tag + article talk", "tag + article talk page (per the rules; unused)", "none", "log-only"),
    ("be_x_oldwiki", 195, "Вікіпэдыя:Кандыдатуры на выдаленьне", "sections on one page, yearly archive", None, "low", "later"),
]


SPECIAL_HOSTS = {"be_x_oldwiki": "be-tarask.wikipedia.org"}


def host(dbname: str) -> str:
    if dbname in SPECIAL_HOSTS:
        return SPECIAL_HOSTS[dbname]
    lang = dbname.removesuffix("wiki").replace("_", "-")
    return f"{lang}.wikipedia.org"


def rows() -> list[dict]:
    out = []
    for db, active, venue, listing, tag_route, volume, plan in SURVEY:
        out.append({
            "wiki": db, "active": active, "venue": venue,
            "venue_url": f"https://{host(db)}/wiki/{quote(venue.replace(' ', '_'), safe=':/()!,\'')}" if venue else None,
            "listing": listing, "tag_route": tag_route, "volume": volume, "plan": plan,
        })
    return out
