"""Покрытие: какие Википедии есть на витрине, какие в очереди, где площадки нет.

Снимок разведки 27–28.09.2026 (43 вики) (stuff/Projects/toolforge/25, 26; data/cee-survey/<db>.md):
активные участники за 30 дней по siteinfo, площадка и число номинаций за август 2026 —
по API. Это справочная таблица для обзора; обновляется руками при новой разведке.

plan: live — раздел в проде; next — в очереди этапа 3; later — площадка есть, но
объём единицы в месяц; log-only — работающей площадки обсуждений нет, только журнал.
"""

from __future__ import annotations

SURVEYED_ON = "2026-09-27/28"

#: (dbname, active editors, venue title or None, how nominations are listed, nominations in Aug 2026, plan)
SURVEY: list[tuple[str, int, str | None, str, str, str]] = [
    ("eswiki", 38963, "Wikipedia:Consultas de borrado", "subpages per nomination, found via category; archive by month", "38", "next"),
    ("frwiki", 34548, "Wikipédia:Débat d'admissibilité", "discussion on the article's talk subpage; live board of links by day", "≈587", "next"),
    ("plwiki", 8856, "Wikipedia:Poczekalnia/artykuły", "dated subpages on a permanent hub, monthly archive", "140 + 66 (biographies)", "next"),
    ("nlwiki", 7864, "Wikipedia:Te beoordelen pagina's", "one page per day (same shape as en/it/ja); no outcome in text, fate from the log", "346", "next"),
    ("ptwiki", 7598, "Wikipédia:Páginas para eliminar", "subpages per nomination, found via category; archive by year", "202", "next"),
    ("fawiki", 7296, "ویکی‌پدیا:نظرخواهی برای حذف", "permanent hub + subpages; creation-month category", "126", "next"),
    ("hewiki", 6628, "ויקיפדיה:רשימת מועמדים למחיקה", "subpages found via a year category, no hub; vote with 55 % threshold", "7", "later"),
    ("arwiki", 5600, "ويكيبيديا:نقاش الحذف", "subpages transcluded on one board", "31", "next"),
    ("kowiki", 5078, "위키백과:삭제 토론", "monthly subpages transcluding nominations (same shape as en/it/ja)", "6", "next"),
    ("viwiki", 5054, "Wikipedia:Biểu quyết xoá bài", "permanent hub grouped by month, archived by month", "35", "next"),
    ("idwiki", 4920, "Wikipedia:Usulan penghapusan", "subpages found via category; no outcome in text, fate from the log", "37", "next"),
    ("svwiki", 4891, "Wikipedia:Sidor föreslagna för radering", "permanent hub + subpages; archive by closing month", "6", "later"),
    ("trwiki", 4213, "Vikipedi:Silinmeye aday sayfalar", "permanent hub, monthly archive", "102", "next"),
    ("cswiki", 4123, "Wikipedie:Diskuse o smazání", "subpages transcluded on a hub list", "16", "next"),
    ("fiwiki", 3536, "Wikipedia:Poistoäänestykset", "queue + yearly category; vote with 70 % threshold", "1", "later"),
    ("simplewiki", 3268, "Wikipedia:Requests for deletion", "queue + subpages Requests/<year>/<title>; closing templates as on en", "84", "next"),
    ("huwiki", 2714, "Wikipédia:Törlésre javasolt lapok", "subpages on a hub grouped by date, monthly archive category", "34", "next"),
    ("thwiki", 2623, None, "a translated policy page with no process behind it; all deletions speedy", "0", "log-only"),
    ("nowiki", 2341, "Wikipedia:Sletting", "queue; a bot archives closed cases by outcome and month; outcome in the heading as on de", "45", "next"),
    ("elwiki", 2270, "Βικιπαίδεια:Σελίδες για διαγραφή", "discussion on the article's talk subpage, monthly index", "6", "next"),
    ("mswiki", 2029, "Wikipedia:Permohonan memadam laman", "daily-log shape with links to pages that do not exist", "1", "later"),
    ("cawiki", 1787, "Viquipèdia:Esborrar pàgines/Propostes", "sections on one page, monthly archive; one admin closes", "1", "later"),
    ("bnwiki", 1735, "উইকিপিডিয়া:নিবন্ধ অপসারণের প্রস্তাবনা", "monthly pages titled with Bengali digits", "6", "later"),
    ("rowiki", 1703, "Wikipedia:Pagini de șters", "subpages transcluded on a hub, monthly ledger of outcomes", "5", "next"),
    ("bgwiki", 1667, "Уикипедия:Страници за изтриване", "dated subpages on a permanent hub", "7–10", "next"),
    ("dawiki", 1659, "Wikipedia:Sletningsforslag", "sections generated by the nomination template, numbered archives; anyone may close", "24", "next"),
    ("srwiki", 1619, "Википедија:Чланци за брисање", "sections on one page, numbered archives; outcome computed from votes", "2", "later"),
    ("skwiki", 1198, "Wikipédia:Stránky na zmazanie", "subpages on a hub, yearly archive", "8", "next"),
    ("hiwiki", 1115, "विकिपीडिया:पृष्ठ हटाने हेतु चर्चा", "found via category; two competing monthly-log formats; closed with XFDcloser", "≈11", "later"),
    ("etwiki", 976, None, "no central venue: article talk page + queue category (624 pages)", "≈59 queued", "log-only"),
    ("hrwiki", 953, "Wikipedija:Rasprava o brisanju", "one page per month, sections", "22", "next"),
    ("azwiki", 849, "Vikipediya:Silinməyə namizəd səhifələr", "subpages transcluded on a hub", "8–25", "next"),
    ("ltwiki", 624, None, "venue dead since 2009; tag + queue category, voting banned", "0", "log-only"),
    ("slwiki", 591, "Wikipedija:Predlogi za brisanje", "subpages on a hub grouped by month", "2", "later"),
    ("uzwiki", 579, "Vikipediya:Oʻchirishga", "subpages transcluded on a hub", "2", "later"),
    ("hywiki", 552, "Վիքիպեդիա:Ջնջման առաջադրված հոդվածներ", "sections on one page; outcome computed from votes (75 %)", "4", "next"),
    ("lvwiki", 498, None, "PROD tag; the voting hub has not handled articles since 2013", "0", "log-only"),
    ("bewiki", 399, "Вікіпедыя:Да выдалення", "sections on one page, yearly archive", "3", "later"),
    ("sqwiki", 370, "Wikipedia:Forumi i Grisjes", "register page, numbered archives", "≈1", "later"),
    ("kkwiki", 369, None, "no venue: the community declined one in 2020", "—", "log-only"),
    ("kawiki", 346, "ვიკიპედია:წაშლილი გვერდების განხილვები", "link hub → subpages; unused", "0", "log-only"),
    ("mkwiki", 324, "Википедија:Статии за бришење", "one page, dead since 2013", "0", "log-only"),
    ("bswiki", 257, None, "rules page only; tag + article talk", "0", "log-only"),
    ("be_x_oldwiki", 195, "Вікіпэдыя:Кандыдатуры на выдаленьне", "sections on one page, yearly archive", "1", "later"),
]


def host(dbname: str) -> str:
    lang = dbname.removesuffix("wiki").replace("_", "-")
    return f"{lang}.wikipedia.org"


def rows() -> list[dict]:
    out = []
    for db, active, venue, listing, per_month, plan in SURVEY:
        out.append({
            "wiki": db, "active": active, "venue": venue,
            "venue_url": f"https://{host(db)}/wiki/{venue.replace(' ', '_')}" if venue else None,
            "listing": listing, "per_month": per_month, "plan": plan,
        })
    return out
